- name: include maven role
  ansible.builtin.include_role:
    name: common
    tasks_from: maven.yml

- name: include app pre_req
  ansible.builtin.include_role:
    name: common
    tasks_from: app_preq.yml

- name:  maven clean package
  ansible.builtin.shell: maven clean package ; mv target/{{component}}-1.0.jar  {{component}}.jar &>>${LOG} # there could be a npm module, However we are still using shell, Since these steps will get removed when CI comes in.
  args:
    chdir: "{{ app_path }}"

- name: include the mysql-schema role
  ansible.builtin.include_role:
    name: common
    tasks_from: mysql_schema.yml
  when: schema_load

- name: include the systemd role
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd.yml




