- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove old html content directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html content directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download and unzip frontend content
  ansible.builtin.file:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /tmp/frontend.zip
    remote_src: yes

- name: copy the roboshop conf
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start and enable nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes