- name: include nodejs role
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yml

- name: include app pre_req
  ansible.builtin.include_role:
    name: common
    tasks_from: app_preq.yml

- name:  Download NodeJS Dependencies
  ansible.builtin.shell: npm install # there could be a npm module, However we are still using shell, Since these steps will get removed when CI comes in.
  args:
    chdir: "{{ app_path }}"

- name: include the mongodb role
  ansible.builtin.include_role:
    name: common
    tasks_from: mongodb_schema.yml
  when: schema_load

- name: include the systemd role
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd.yml



