- name: disable MySQL 8 version.
  ansible.builtin.shell: dnf module disable mysql -y

- name: copy the mysql repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.dnf:
    name:  mysql-community-server

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setup MySQL Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{mysql_root_password}}