- name: set-up the prometheus server
  ansible.builtin.include_tasks: "server.yml"
  when: prometheus == "server"

- name: set-up the prometheus-exporter
  ansible.builtin.include_tasks: "exporter.yml"
  when: prometheus == "exporter"