- name: install python deps
  ansible.builtin.yum:
    name:
     - python3-PyMySQL
     - mysql
    state: installed

- name: Load MySQL Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: mysql-dev.chandrap.shop
    login_user: root
    login_password: "{{root_mysql_password}}"
