- name: include nodejs role
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yml

- name: include app pre_req
  ansible.builtin.include_role:
    name: common
    tasks_from: app_preq.yml

- name: Install Nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: include the systemd role
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd.yml




